### PR TITLE
Fix distance sensor returning max distance incorrectly

### PR DESCRIPTION
**Pull request by WillB97**
Certain surfaces of the arena were not being detected by the distance sensors resulting in the sensors returning their maximum distance even when next to, and parallel to, the wall.
To remedy this the arena has been reconstructed using simple block shapes. It was additionally discovered that webots currently suffers this same issue with the TexturedBox object.

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
Not sure I'm really the right person to review this as I made most of the changes?

**Review by sedders123 — DISMISSED** [review]
Changes seem reasonable and I've had a play locally and the numbers reported by the sensors seem to be correct 🎉

**Comment by sedders123** [comment]
This image doesn't look right to me, back left doesn't look like it should be 2
image

**Comment by PeterJCLaw** [comment]
> This image doesn't look right to me, back left doesn't look like it should be 2
> image

Bear in mind that at high angles to the walls we don't expect the sensors to work. Can you reproduce with the sensor more perpendicular to the wall?

**Comment by sedders123** [comment]
> Bear in mind that at high angles to the walls we don't expect the sensors to work.
Ahh wasn't aware of that. When more perpendicular the numbers seen fine!

**Review by sedders123 — APPROVED** [review]

**Pull request merged**
