### PR TITLE
Ban accidental usage of 'print'

### PR DESCRIPTION
**Pull request by PeterJCLaw**
Aims to avoid `print` statements from debugging making their way into `master`.

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
The `example_controller.py` contains prints, but they don't seem to be ignored. Is that file being linted (properly)?

**Comment by PeterJCLaw** [comment]
> The `example_controller.py` contains prints, but they don't seem to be ignored. Is that file being linted (properly)?

good spot, it wasn't. I'll fix that.

**Comment by RealOrangeOne** [comment]
My main query was that even though there's a `print` in the `example_controller.py`, tests aren't failing, which makes me think linting isn't being run on it?

**Comment by PeterJCLaw** [comment]
It indeed wasn't. I fixed that separately in https://github.com/srobo/competition-simulator/commit/5dd4364b8c148cf4087c2eab2ca4e51ec585418c.

**Pull request merged**
