### PR TITLE
Minimally prepare the arena for a point-zero release

### PR DESCRIPTION
**Pull request by PeterJCLaw**
This is stripped out enough to allow us to do a release which will let teams confirm that they have installed the simulator correctly, without containing anything specific to this year's game.

Review in part also for "is this a good idea".

### CODE REVIEW

**Comment by WillB97** [comment]
Doesn't this require teams to install the simulator twice in a period of 5 days?

**Comment by PeterJCLaw** [comment]
> Doesn't this require teams to install the simulator twice in a period of 5 days?

Why? We're not referencing a different version of Webots.

**Comment by PeterJCLaw** [comment]
If you mean the simulation (i.e: the world etc.) then yes, however the simulation files are small and upgrading them is something that the teams should be able to do anyway. (If they can't then it's probably better that they find that out at Kickstart rather than later).

**Review by Adimote — APPROVED** [review]

**Comment by PeterJCLaw** [comment]
We ended up not shipping this.

**Pull request closed without merging**
